---
title: "Rmarkdown"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```



::: {.box-header}
`r fontawesome::fa_i("bullseye")`
L'objectif de cet exercice est de vous familiariser à l'utilisation de **`Rmarkdown`**. Plus précisément, vous verrez comment exécuter l'ensemble des analyses et la rédaction dans un même fichier `.Rmd`.
:::


<br />

## Consignes

Nous allons utiliser les données WildFinder du WWF pour répondre à la question suivante :
**_Dans combien d'écorégions différentes retrouve-t-on chaque espèce d'Ursidés ?_**

Pour ce faire, continuez à travailler dans le **research compendium** créé lors de l'exercice 1 et écrivez des fonctions 
`r fontawesome::fa_i("r-project")` pour : 

- Importer chaque fichier `csv` (utiliser la fonction `readr::read_csv()`)
- Sélectionner uniquement les espèces de la famille des Ursidae
- Joindre les trois tables entre elles
- Compter le nombre d'écorégions où se retrouve chaque espèce
- Faire une visualisation graphique montrant le nombre d'écorégions par espèce

Puis, créez un fichier `index.Rmd` à la racine du projet qui appellera chaque fonction créée précédemment. Devrons figurer dans le document final, a minima, le résultat demandé sous forme de tableau (fonction `knitr::kable()`) et de figure, ainsi que la source des données.

Finalement, ajoutez une ligne de code dans votre `make.R` qui permettra de transpiler votre `index.Rmd` en version `index.html` (fonction `rmarkdown::render()`).

`r fontawesome::fa_i("lightbulb")` Pensez aux commits !


<br />

## Bonus

Si votre code est bien écrit, vous pouvez rapidement l'exécuter avec une autre famille de Mammifères !

## Corrections {.appendix}


If you see mistakes or want to suggest changes, please 
[Create an issue](https://github.com/rdatatoolbox/rdatatoolbox.github.io/issues)
on the source repository.



## Reuse {.appendix}



The material of this website is licensed under Creative Commons Attribution 
[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/).
Source code is available at https://github.com/rdatatoolbox/rdatatoolbox.github.io/.


## Citation {.appendix}



Casajus N, Bonnici I, Dray S, Gimenez O, Guéry L, Guilhaumon F, Schiettekatte NMD & Siberchicot A (2022) 
Workshop FRB-CESAB & GdR EcoStat: Data Toolbox for Reproducible Research in Computational Ecology. 
Zenodo. <http://doi.org/10.5281/zenodo.4262978>.
