---
title: "Renv"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```



::: {.box-header}
`r fontawesome::fa_i("bullseye")`
L'objectif de cet exercice est de vous familiariser avec l'utilisation de **`renv`**, package `r fontawesome::fa_i("r-project")` permettant de gérer les versions de packages requises par le projet.
:::



<br />

## Consignes

Nous allons intégrer `renv` au **research compendium** créé lors de l'exercice 4.

- Utilisez la fonction `rcompendium::add_renv()`
- Ajoutez le dossier `renv/` et le ficher `.Rprofile` au `.gitignore` (afin de ne pas envoyer sur GitHub les packages - seul le `renv.lock` suffit)
- Jouez avec les fonctions `renv::status()`, `renv::install()` et `renv::snapshot()` (n'oubliez pas de mettre à jour la liste des dépendances dans le fichiers **`DESCRIPTION`**)
- Modifiez le `make.R` de manière à installer les packages via `renv` plutôt qu'avec la fonction `devtools::install_deps()`
- Vérifiez si votre projet est encore exécutable en source le `make.R`


`r fontawesome::fa_i("lightbulb")` Pensez aux **commits** !



## Corrections {.appendix}


If you see mistakes or want to suggest changes, please 
[Create an issue](https://github.com/rdatatoolbox/rdatatoolbox.github.io/issues)
on the source repository.



## Reuse {.appendix}



The material of this website is licensed under Creative Commons Attribution 
[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/).
Source code is available at https://github.com/rdatatoolbox/rdatatoolbox.github.io/.


## Citation {.appendix}



Casajus N, Bonnici I, Dray S, Gimenez O, Guéry L, Guilhaumon F, Schiettekatte NMD & Siberchicot A (2022) 
Workshop FRB-CESAB & GdR EcoStat: Data Toolbox for Reproducible Research in Computational Ecology. 
Zenodo. <http://doi.org/10.5281/zenodo.4262978>.
