---
toc: true
---

# Welcome {.unnumbered}

::: {.callout-note}
## Registrations to the training course

Registrations open each spring and the training course takes place during the fall. 

{{< fa hand-point-right >}}&nbsp; Subscribe to the 
[FRB-CESAB newsletter](https://www.fondationbiodiversite.fr/en/newsletter/) 
to stay informed. More information is available on the [FRB-CESAB website](https://www.fondationbiodiversite.fr/en/the-frb-in-action/programs-and-projects/le-cesab/develop-skills/best-practice-for-reproducible-research-in-computational-ecology/).
:::



The objective of this five-day training course, co-organized by the 
[FRB-CESAB](https://www.fondationbiodiversite.fr/en/about-the-foundation/le-cesab/)
and the
[RT EcoStat](https://sites.google.com/site/gdrecostat/), 
is to train researchers in reproducibility, software development and 
version control tools (e.g. `git`, `GitHub`, `Quarto`, `renv` & `Docker`), 
applied to biodiversity research.


## Program {.unnumbered}

**MONDAY** - Open science, Research compendium, Functions & Packages

{{< fa display >}} &nbsp; Welcome & Opening remarks
<br/>
{{< fa display >}} &nbsp; **Open science** & **Reproducible research**
<br/>
[Coffee break]{.gray}
<br/>
{{< fa display >}} &nbsp; Introduction to **Positron IDE**
<br/>
{{< fa display >}} &nbsp; Organizing your project as a **Research compendium**
<br/>
{{< fa code >}} &nbsp; **Hands-on session:** Building my first research compendium
<br/>
[Lunch break]{.gray}
<br/>
{{< fa display >}} &nbsp; Refactoring scripts into **R Functions**
<br/>
{{< fa code >}} &nbsp; **Hands-on session:** Refactoring the research compendium scripts into functions
<br/>
{{< fa display >}} &nbsp; The **`DESCRIPTION`** file
<br/>
{{< fa code >}} &nbsp; **Hands-on session:** Adding a `DESCRIPTION` file to your research compendium
<br/>
[Coffee break]{.gray}
<br/>
{{< fa display >}} &nbsp; Developing an **R Package**


<br/>


**TUESDAY** - Version control & targets

{{< fa display >}} &nbsp; Introduction to **`git`** – Part 1: **Initialization & Commits**
<br/>
{{< fa code >}} &nbsp; **Hands-on session:** Initializing and using `git` in your research compendium
<br/>
[Coffee break]{.gray}
<br/>
{{< fa display >}} &nbsp; Introduction to **`git`** – Part 2: **Pushing to GitHub**
<br/>
{{< fa code >}} &nbsp; **Hands-on session:** Publishing your research compendium on GitHub
<br/>
[Lunch break]{.gray}
<br/>
{{< fa display >}} &nbsp; Optimizing your workflow with **`{targets}`**
<br/>
[Coffee break]{.gray}
<br/>
{{< fa code >}} &nbsp; **Hands-on session:** Integrating `{targets}` into your research compendium


<br/>


**WEDNESDAY** - Version control, GitHub & Quarto

{{< fa display >}} &nbsp; Introduction to **`git`** – Part 3: **Collaboration and Conflict resolution**
<br/>
[Coffee break]{.gray}
<br/>
{{< fa code >}} &nbsp; **Hands-on session:** Collaborating on the same project
<br/>
[Lunch break]{.gray}
<br/>
{{< fa display >}} &nbsp; Code hosting platforms: **GitHub**, **GitLab** & **Codeberg**
<br/>
{{< fa display >}} &nbsp; Literate programming with **Quarto**
<br/>
[Coffee break]{.gray}
<br/>
{{< fa code >}} &nbsp; **Hands-on session:** Adding Quarto to your research compendium


<br/>


**THURSDAY** - renv, Docker & Group projects

{{< fa display >}} &nbsp; Managing packages and their versions with **`{renv}`**
<br/>
{{< fa code >}} &nbsp; **Hands-on session:** Adding `{renv}` to your research compendium
<br/>
[Coffee break]{.gray}
<br/>
{{< fa display >}} &nbsp; Containerizing your project with **Docker**
<br/>
{{< fa display >}} &nbsp; Week recap and formation of project groups
<br/>
[Lunch break]{.gray}
<br/>
{{< fa users-line >}} &nbsp; Group projects


<br/>


**FRIDAY** - Group projects

{{< fa users-line >}} &nbsp; Group projects
<br/>
[Lunch break]{.gray}
<br/>
{{< fa users-line >}} &nbsp; Group project presentations



## Prerequisites {.unnumbered}

{{< fa hand-point-right >}}&nbsp; Please follow this [tutorial](https://frbcesab.github.io/rsetup/chapters/reproducible-research.html) to install 
your working environment **before attending the training course**.

{{< fa hand-point-right >}}&nbsp; You also need to create an account on [GitHub](https://github.com/signup/) (please edit your profile and enter your name).


## Material {.unnumbered}

All the material used in this training course (slides, data, exercises) is available at: <https://github.com/rdatatoolbox/>



## Citation {.unnumbered}

> Casajus N, Bonnici I, Dray S, Gimenez O, Guéry L, Guilhaumon F, Schiettekatte NMD 
& Siberchicot A (2026) 
FRB-CESAB & RT EcoStat Training Course: Reproducible Research in Computational Ecology. 
Zenodo. URL: <http://doi.org/10.5281/zenodo.4262978>


## Contributions {.unnumbered}

If you see mistakes or want to suggest changes, please [create an issue](https://github.com/rdatatoolbox/rdatatoolbox.github.io/issues/new) on the source repository.


## Reuse {.unnumbered}

Text and figures are licensed under Creative Commons Attribution [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/), unless otherwise noted.


## See also {.unnumbered}


Discover the other training courses provided by the FRB-CESAB and its partners: <https://frbcesab.github.io/training-courses/>
