## Docker {.unnumbered}

::: {.callout-note}
## Objectif

L'objectif de cet exercice est de vous familiariser avec l'utilisation de `Docker`, et plus particulièrement avec la création d'un **`Dockerfile`**.
:::


### Consignes {.unnumbered}

Nous allons ajouter un [Dockerfile](https://docs.docker.com/engine/reference/builder/) au **research compendium** créé lors de l'[exercice 5](https://rdatatoolbox.github.io/chapters/ex-renv.html).

- Utilisez la fonction [`rcompendium::add_dockerfile()`](https://frbcesab.github.io/rcompendium/reference/add_dockerfile.html) (désactivez temporairement [`renv`](https://rstudio.github.io/renv/articles/renv.html) avec [`renv::deactivate()`](https://rstudio.github.io/renv/reference/activate.html) le temps d'utiliser cette fonction, puis réactivez-le avec [`renv::activate()`](https://rstudio.github.io/renv/reference/activate.html))
- Réfléchissez si la version de l'image de base `rocker/rstudio:4.3.2` est la plus appropriée à votre projet
- Regardez le contenu du **README.Rmd** : doit-il être transpilé ?
- Suivez les instructions du **README.md** pour construire votre image, démarrez un conteneur et relancer les analyses.


{{< fa lightbulb >}}&nbsp; Pensez aux **commits** !

> Félicitation ! Votre project est 99,99% reproductible.
